version: '3.8'

services:
    db:
        restart: always
        image: mysql/mysql-server:8.0
        container_name: mlflow_db
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=mlflow
            - MYSQL_USER=mlflow
            - MYSQL_PASSWORD=mlflow
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

    web:
        restart: always
        build: ./mlflow
        image: mlflow_server
        container_name: mlflow_server
        depends_on:
            - db
        ports:
            - "5000:5000"
        environment:
            - MLFLOW_S3_ENDPOINT_URL=https://storage.yandexcloud.net
            - AWS_ACCESS_KEY_ID=${YC_ACCESS_KEY_ID:-your_key_id_here}
            - AWS_SECRET_ACCESS_KEY=${YC_SECRET_ACCESS_KEY:-your_secret_key_here}
            - MLFLOW_S3_IGNORE_TLS=true
            - MLFLOW_TRACKING_URI=http://localhost:5000
            - MLFLOW_DEFAULT_ARTIFACT_ROOT=s3://vkr-images/mlflow/
        command: mlflow server --backend-store-uri mysql+pymysql://mlflow:mlflow@db:3306/mlflow --host 0.0.0.0 --port 5000
        networks:
            - app-network

    redis:
        image: redis:latest
        container_name: redis
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
            - "6379:6379"
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
            - redis_data:/data
        restart: unless-stopped
        networks:
            - app-network

    backend:
        build: ./backend
        container_name: backend
        depends_on:
            - redis
            - web
        ports:
            - "5002:5002"
        environment:
            - REDIS_HOST=redis
            - MLFLOW_TRACKING_URI=http://web:5000
        volumes:
            - ./backend/images:/app/images
            - ./backend/artifacts:/app/artifacts
        restart: unless-stopped
        networks:
            - app-network

    front:
        build: ./front
        container_name: front
        ports:
            - "3000:3000"
        depends_on:
            - backend
        environment:
            - NEXT_PUBLIC_BACKEND_URL=http://localhost:5002
            - NEXT_PUBLIC_PRODUCTION_BACKEND_URL=https://api.nevermoxsw.tech
        restart: unless-stopped
        networks:
            - app-network

volumes:
    dbdata:
    redis_data:

networks:
    app-network:
        driver: bridge 